<Project>
  <PropertyGroup>
    <EnableCentralPackageVersions>true</EnableCentralPackageVersions>
    <TargetFramework>native</TargetFramework>
    <RestoreAdditionalProjectSources>
      <!-- for lua dependency -->
      https://api.nuget.org/v3/index.json;       
    
    </RestoreAdditionalProjectSources>
    <_NuGetTargetFallbackMoniker>$(_NuGetTargetFallbackMoniker);native,Version=v0.0</_NuGetTargetFallbackMoniker>
  </PropertyGroup>

  <ItemGroup>
    <!-- lua is a dependency that should be forwarded upon those that use the nuget package -->
	<PackageReference Include="lua" Version="5.4.6" PrivateAssets="none" ExcludeAssets="none" IncludeAssets="all" />
    <PackageReference Include="DirectX_8" Version="8.0.0" />

  </ItemGroup>
</Project>
